=== GreatestCaesar/Labs/PD_PL/Practical8/out/production/Practical8/by/bsac/practical8/individual/gem.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Gem" type="GemType"/>
  <xs:complexType name="visual_parametersType">
    <xs:sequence>
      <xs:element name="color">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Бесцветный"/>
            <xs:enumeration value="Фиолетовый"/>
            <xs:enumeration value="Зеленый"/>
            <xs:enumeration value="Жёлтый"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="transparence">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="100"/>
            <xs:enumeration value="50"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="gemType">
    <xs:sequence>
      <xs:element name="name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Алмаз"/>
            <xs:enumeration value="Аметист"/>
            <xs:enumeration value="Изумруд"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="preciousness">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Драгоценный"/>
            <xs:enumeration value="Полудрагоценный"/>
            <xs:enumeration value="Полдрагоценный"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="origin">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Россия"/>
            <xs:enumeration value="Африка"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="visual_parametersType" name="visual_parameters"/>
      <xs:element name="value">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="10"/>
            <xs:enumeration value="4"/>
            <xs:enumeration value="13"/>
            <xs:enumeration value="6"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="GemType">
    <xs:sequence>
      <xs:element type="gemType" name="gem" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== GreatestCaesar/Labs/PD_PL/Practical8/out/production/Practical8/by/bsac/practical8/individual/gem.xml
<?xml version="1.0" encoding="UTF-8"?>

<Gem>
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="gem.xsd">
    <gem>
        <name>Алмаз</name>
        <preciousness>Драгоценный</preciousness>
        <origin>Россия</origin>
        <visual_parameters>
            <color>Бесцветный</color>
            <transparence>100</transparence>
        </visual_parameters>
        <value>10</value>
    </gem>
    <gem>
        <name>Аметист</name>
        <preciousness>Полудрагоценный</preciousness>
        <origin>Россия</origin>
        <visual_parameters>
            <color>Фиолетовый</color>
            <transparence>100</transparence>
        </visual_parameters>
        <value>4</value>
    </gem>
    <gem>
        <name>Изумруд</name>
        <preciousness>Драгоценный</preciousness>
        <origin>Россия</origin>
        <visual_parameters>
            <color>Зеленый</color>
            <transparence>100</transparence>
        </visual_parameters>
        <value>13</value>
    </gem>
    <gem>
        <name>Алмаз</name>
        <preciousness>Поулдрагоценный</preciousness>
        <origin>Африка</origin>
        <visual_parameters>
            <color>Жёлтый</color>
            <transparence>50</transparence>
        </visual_parameters>
        <value>6</value>
    </gem>
</Gem>
